// Tile notation: # wall, _ floor, T target, B box, P player,
// X box-on-target, Q player-on-target. See docs/superpowers/specs/
// 2026-09-02-sokoban-moving-boxes-design.md for the full design.
//
// Each level is a single connected maze (rooms + corridors + pillars),
// verified solvable by the BFS checker in tests/solver.js — box/target
// pairing is flexible (any box may settle on any target).

export const LEVELS = [
  {
    floor: 1,
    name: 'First Steps',
    text: [
      '#######',
      '#__T__#',
      '#__#__#',
      '#P_B__#',
      '#_____#',
      '#######',
    ].join('\n'),
  },
  {
    floor: 2,
    name: 'Around the Pillar',
    text: [
      '#########',
      '#P__#___#',
      '#_#_#_#_#',
      '#_B___T_#',
      '#_#_#_#_#',
      '#___#___#',
      '#########',
    ].join('\n'),
  },
  {
    floor: 3,
    name: 'Twin Chambers',
    text: [
      '#########',
      '#___#___#',
      '#_B_#_T_#',
      '#___#___#',
      '#P______#',
      '#___#___#',
      '#_B_#_T_#',
      '#___#___#',
      '#########',
    ].join('\n'),
  },
  {
    floor: 4,
    name: 'Three Rooms',
    text: [
      '########',
      '#P_#___#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#__#___#',
      '########',
    ].join('\n'),
  },
  {
    floor: 5,
    name: 'The Winding Hall',
    text: [
      '########',
      '#P_#___#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#__#___#',
      '########',
    ].join('\n'),
  },
  {
    floor: 6,
    name: 'The Winding Hall (Mirror)',
    text: [
      '########',
      '#P_#___#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#__#___#',
      '########',
    ].join('\n'),
  },
  {
    floor: 7,
    name: 'Four Chambers',
    text: [
      '########',
      '#P_#___#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#__#___#',
      '########',
    ].join('\n'),
  },
  {
    floor: 8,
    name: 'Four Chambers (Mirror)',
    text: [
      '########',
      '#P_#___#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#__#___#',
      '########',
    ].join('\n'),
  },
  {
    floor: 9,
    name: 'Top Floor Maze',
    text: [
      '########',
      '#P_#___#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#__#___#',
      '########',
    ].join('\n'),
  },
  {
    floor: 10,
    name: 'Top Floor Maze (Mirror)',
    text: [
      '########',
      '#P_#___#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#_B_T__#',
      '#_###_#_',
      '#_B_T__#',
      '#_#_#_#_',
      '#__#___#',
      '########',
    ].join('\n'),
  },
];
