// Tile notation: # wall, _ floor, T target, B box, P player,
// X box-on-target, Q player-on-target. See docs/superpowers/specs/
// 2026-09-02-sokoban-moving-boxes-design.md for the full design.

export const LEVELS = [
  {
    floor: 1,
    name: 'First Steps',
    text: ['#####', '#TBP#', '#####'].join('\n'),
  },
  {
    floor: 2,
    name: 'Long Hall',
    text: ['#########', '#P__B__T#', '#########'].join('\n'),
  },
  {
    floor: 3,
    name: 'Two Rooms',
    text: [
      '#########',
      '#P_B__T_#',
      '#_#######',
      '#__B__T_#',
      '#########',
    ].join('\n'),
  },
  {
    floor: 4,
    name: 'Three Rooms',
    text: [
      '#########',
      '#P_B__T_#',
      '#_#######',
      '#__B__T_#',
      '#_#######',
      '#__B__T_#',
      '#########',
    ].join('\n'),
  },
  {
    floor: 5,
    name: 'The Stretch',
    text: [
      '###########',
      '#P_B____T_#',
      '#_#########',
      '#__B____T_#',
      '#_#########',
      '#__B____T_#',
      '###########',
    ].join('\n'),
  },
  {
    floor: 6,
    name: 'Four Rooms',
    text: [
      '#########',
      '#P_B__T_#',
      '#_#######',
      '#__B__T_#',
      '#_#######',
      '#__B__T_#',
      '#_#######',
      '#__B__T_#',
      '#########',
    ].join('\n'),
  },
  {
    floor: 7,
    name: 'Four Stretched',
    text: [
      '###########',
      '#P_B____T_#',
      '#_#########',
      '#__B____T_#',
      '#_#########',
      '#__B____T_#',
      '#_#########',
      '#__B____T_#',
      '###########',
    ].join('\n'),
  },
  {
    floor: 8,
    name: 'The Long Four',
    text: [
      '#############',
      '#P_B______T_#',
      '#_###########',
      '#__B______T_#',
      '#_###########',
      '#__B______T_#',
      '#_###########',
      '#__B______T_#',
      '#############',
    ].join('\n'),
  },
  {
    floor: 9,
    name: 'Five Rooms',
    text: [
      '#########',
      '#P_B__T_#',
      '#_#######',
      '#__B__T_#',
      '#_#######',
      '#__B__T_#',
      '#_#######',
      '#__B__T_#',
      '#_#######',
      '#__B__T_#',
      '#########',
    ].join('\n'),
  },
  {
    floor: 10,
    name: 'Top Floor',
    text: [
      '##########',
      '#P_B___T_#',
      '#_########',
      '#__B___T_#',
      '#_########',
      '#__B___T_#',
      '#_########',
      '#__B___T_#',
      '#_########',
      '#__B___T_#',
      '##########',
    ].join('\n'),
  },
];
